server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /model-1/ {
        alias /usr/share/nginx/html/model-1/;
        try_files $uri $uri/ /model-1/index.html;
    }

    location /model-2/ {
        alias /usr/share/nginx/html/model-2/;
        try_files $uri $uri/ /model-2/index.html;
    }

    location /model-3/ {
        alias /usr/share/nginx/html/model-3/;
        try_files $uri $uri/ /model-3/index.html;
    }
}
